FROM alpine:latest

ARG QEMU_USER_STATIC_ARCH

LABEL org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url="https://github.com/microscotch/docker-bind9"

COPY qemu-${QEMU_USER_STATIC_ARCH}-static /usr/bin/

RUN apk --update add bind && rm /usr/bin/qemu-${QEMU_USER_STATIC_ARCH}-static

FROM scratch

COPY --from=builder / /

EXPOSE 53

CMD ["named", "-c", "/etc/bind/named.conf", "-g", "-u", "named"]
